version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: pro_padel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pro_padel
    ports:
      - "5432:5432"
